"""empty message

Revision ID: 873edf2db8db
Revises: ca5e26fc0cb5
Create Date: 2017-04-30 21:00:40.974000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873edf2db8db'
down_revision = 'ca5e26fc0cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
